name: 'Scan docker image vulnerability using Trivy'
description: 'Scan docker image vulnerability and create issue'
author: 'homoluctus'
inputs:
  token:
    description: 'GitHub access token'
    required: true
  trivy_version:
    description: 'Trivy version'
    default: 'latest'
    required: false
  image:
    description: 'The target image name of vulnerability scan'
    required: true
  severity:
    description: 'sevirities of vulunerabilities (separeted by commma)'
    default: 'HIGH,CRITICAL'
    required: false
  vuln_type:
    description: 'target vlunerability [os,library] (separeted by commma)'
    default: 'os,library'
    required: false
  ignore_unfixed:
    description: 'Ignore unfixed vulnerabilities [true, false]'
    default: 'false'
    required: false
  issue_title:
    description: 'Issue title'
    default: 'Security Alert'
    required: false
  issue_label:
    description: 'Issue label (separeted by commma)'
    default: 'trivy,vulnerability'
    required: false
  issue_assignee:
    description: 'Issue assignee (separeted by commma)'
    required: false

outputs:
  issue_number:
    description: 'The created issue number'
  html_url:
    description: 'The URL to view the issue'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'search'
  color: 'blue'