name: Integration Test

on:
  pull_request:
    paths:
      - 'dist/**'
  workflow_dispatch:

env:
  IMAGE_NAME: knqyf263/vuln-image

jobs:
  test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull ${{ env.IMAGE_NAME }}

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ env.IMAGE_NAME }}
        issue_label: trivy,vulnerability,test
        issue_title: Security Alert Test
        issue_assignee: homoluctus
